# Funding options for the Public Radio Agents project
# GitHub will display these options on the repository page

# GitHub Sponsors
# github: tmoody1973

# Other funding platforms
# ko_fi: publicradioagents
# patreon: publicradioagents

# Custom funding URLs
custom: ["https://github.com/tmoody1973/public-radio-agents#contributing"]